### ISSUE TITLE
[BUG] terra-gamescope crashes due to DMABUF bug

### ISSUE THREAD

**Issue by korewaChino** [terrapkg/packages#1909]
**Describe the bug**
```
gamescope: types/wlr_linux_dmabuf_v1.c:532: feedback_compile: Assertion `table_len > 0' failed
```

**To Reproduce**
1. Install terra-gamescope
2. Try to launch gamescope

**Expected behavior**
Gamescope launches properly and selects a GPU, launching successfully

**Screenshots**
![image](https://github.com/user-attachments/assets/d8d1b342-3a0d-423c-9cd0-75ee55a2e6fb)

**Affected (please complete the following information):**
 - Fedora, Ultramarine
 - Package terra-gamescope

**Additional context**
Might be caused by one of the patches,

`inxi -G` output:
```
Graphics:
  Device-1: AMD Ellesmere [Radeon RX 470/480/570/570X/580/580X/590]
    driver: amdgpu v: kernel
  Display: wayland server: X.org v: 1.20.14 with: Xwayland v: 24.1.2
    compositor: kwin_wayland driver: N/A resolution: 1920x1080
  API: EGL v: 1.5 drivers: kms_swrast,radeonsi,swrast
    platforms: gbm,wayland,x11,surfaceless,device
  API: OpenGL v: 4.6 compat-v: 4.5 vendor: amd mesa v: 24.1.5 renderer: AMD
    Radeon RX 580 Series (radeonsi polaris10 LLVM 18.1.6 DRM 3.57
    6.10.3-200.fc40.x86_64)
  API: Vulkan v: 1.3.283 drivers: N/A surfaces: xcb,xlib,wayland
```
